### ISSUE TITLE
Not able to run in x86 in CPU

### ISSUE THREAD

**Issue by navaravan** [xingyizhou/GTR#14]
Hi @xingyizhou @noahcao 
Thank you for sharing this work
When I'm trying to run the script in my x86 machine in cpu  **$python demo.py --config-file configs/GTR_TAO_DR2101.yaml --video-input docs/yfcc_v_acef1cb6d38c2beab6e69e266e234f.mp4 --output output/demo_yfcc.mp4 --opts MODEL.WEIGHTS GTR_TAO_DR2101.pth**,  I'm getting the following error:

Traceback (most recent call last):
  File "/home/sravan/SAT/Tracker/GTR/demo.py", line 161, in <module>
    for vis_frame in demo.run_on_video(video):
  File "/home/sravan/SAT/Tracker/GTR/gtr/predictor.py", line 147, in run_on_video
    outputs = self.video_predictor(frames)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/sravan/SAT/Tracker/GTR/gtr/predictor.py", line 103, in __call__
    predictions = self.model(inputs)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sravan/SAT/Tracker/GTR/gtr/modeling/meta_arch/gtr_rcnn.py", line 61, in forward
    return self.sliding_inference(batched_inputs)
  File "/home/sravan/SAT/Tracker/GTR/gtr/modeling/meta_arch/gtr_rcnn.py", line 81, in sliding_inference
    instances_wo_id = self.inference(
  File "/home/sravan/SAT/Tracker/GTR/gtr/modeling/meta_arch/custom_rcnn.py", line 107, in inference
    features = self.backbone(images.tensor)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/detectron2/modeling/backbone/fpn.py", line 126, in forward
    bottom_up_features = self.bottom_up(x)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sravan/SAT/Tracker/GTR/third_party/CenterNet2/centernet/modeling/backbone/res2net.py", line 630, in forward
    x = stage(x)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sravan/SAT/Tracker/GTR/third_party/CenterNet2/centernet/modeling/backbone/res2net.py", line 457, in forward
    sp = self.convs[i](sp, offset, mask)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/detectron2/layers/deform_conv.py", line 474, in forward
    x = modulated_deform_conv(
  File "/home/sravan/anaconda3/lib/python3.9/site-packages/detectron2/layers/deform_conv.py", line 211, in forward
    raise NotImplementedError("Deformable Conv is not supported on CPUs!")
NotImplementedError: Deformable Conv is not supported on CPUs!

How can I solve this?

**Comment by xingyizhou** [comment]
Hi,

  Thank you for your interest. Unfortunately, our demo model does not run on CPU due to its use of deformable convolutional layers. We do not plan to support it on CPU, however your can train your own model for CPU by removing the DCN layers [here](https://github.com/xingyizhou/GTR/blob/master/configs/GTR_TAO_DR2101.yaml#L11).

Best,
Xingyi

**Comment by navaravan** [comment]
Hi @xingyizhou 
Thanks for the reply.
